Write a program which accepts month's name as input and display the number of days in the month as output

In [5]:
def get_days_in_month(month_name):
    # Define the days in each month
    months_with_days = {
        "January": 31,
        "February": 28,  # Assuming non-leap year
        "March": 31,
        "April": 30,
        "May": 31,
        "June": 30,
        "July": 31,
        "August": 31,
        "September": 30,
        "October": 31,
        "November": 30,
        "December": 31
    }

    # Normalize input to have proper capitalization
    month_name = month_name.strip().capitalize()

    # Use a for loop to check if the month exists in the dictionary
    for month in months_with_days:
        if month_name == month:
            return months_with_days[month]

    # If we exit the loop, the month is invalid
    return "Invalid month name!"

# Accept input from the user
month_name = input("Enter the name of the month: ").strip().capitalize()

# Get and display the number of days
days = get_days_in_month(month_name)
print(f"The number of days in {month_name} is {days}.")

Enter the name of the month: january
The number of days in January is 31.

Write a program to separate even and odd numbers in two distinct lists from a list of numbers of your choice

In [9]:
  numbers = [12, 45, 67, 23, 8, 34, 56, 89, 90, 13]

  even_numbers = []
  odd_numbers = []

  for num in numbers:
    if num % 2 == 0:
      even_numbers.append(num)
    else:
      odd_numbers.append(num)


  print("Even numbers", even_numbers)
  print("Odd Numbers", odd_numbers)

Even numbers [12, 8, 34, 56, 90]
Odd Numbers [45, 67, 23, 89, 13]

Write a program that appends datatype of elements from a list to a separate list

In [10]:
mixed_list = [12, "Hello", 3.14, True, None, [1, 2, 3], {'key': 'value'}, (1, 2)]

type_list = []


for element in mixed_list:
  type_list.append(type(element))

print("Data types of element ", type_list)

Data types of element  [<class 'int'>, <class 'str'>, <class 'float'>, <class 'bool'>, <class 'NoneType'>, <class 'list'>, <class 'dict'>, <class 'tuple'>]

Write a program to display only those numbers from a list that satisfies the following conditions:

1. The number must be divisible by 7

2. If the number is 140 then skip it and move to the next number in the list

3. If the number in the list is greater than 630 then stop the loop

In [15]:
numbers = [49, 70, 140, 35, 126, 210, 98, 630, 700, 800]

for num in numbers:

    if num % 7 == 0:

      if num ==140:

        continue

      if num > 630:
        break

      print(num)

In [16]:
# List of numbers
numbers = [49, 70, 140, 35, 126, 210, 98, 630, 700, 800]

# Loop through the numbers
for num in numbers:
    # Check if the number is divisible by 7
    if num % 7 == 0:
        # Skip the number 140
        if num == 140:
            continue
        # Stop the loop if the number is greater than 630
        if num > 630:
            break
        # Print the valid number
        print(num)

49
70
35
126
210
98
630